"""Initial schema with new fields

Revision ID: 03cdcde0798c
Revises: de081ffeb42d
Create Date: 2026-01-19 06:46:54.104978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cdcde0798c'
down_revision: Union[str, None] = 'de081ffeb42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('financial_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('platform_domain', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('order_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_name')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'platform_domain')
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'financial_status')
    op.drop_column('orders', 'currency')
    # ### end Alembic commands ###
