"""Add full_data column

Revision ID: de081ffeb42d
Revises: 
Create Date: 2026-01-19 03:46:17.090246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de081ffeb42d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('full_data', sa.JSON(), nullable=True))
    op.drop_column('orders', 'print_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('print_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'full_data')
    # ### end Alembic commands ###
